---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-client
  labels:
    death-star-project: hotel-res
    app: hr-client
  namespace: hotel-res
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app: hr-client
  template:
    metadata:
      labels: 
        death-star-project: hotel-res
        app: hr-client
      name: hr-client
#      annotations:
#        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: hr-client
        image: ubuntu
        command:  ["/bin/sh", "-c"]
        args:
          - apt-get -y update &&
            apt-get -y upgrade &&
            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
            luarocks install luasocket &&
            sleep 365d
        imagePullPolicy: Always
        restartPolicy: Always

