---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    # - name: Pull the images of containers used for DSB
    #   shell: >
    #         docker pull {{item}}
    #   with_items:
    #     - "{{ apps[app]['containers']['to_pull'] }}"


    - name: Build the images of containers used for DSB
      shell: >
            cd /home/jfloff/nas_inesc/antipode/antipode-deathstarbench ;
            pip3 install -r requirements.txt ;
            ./maestro.py {{ app }} --local build
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"
