---
- hosts: all
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Check if Docker is installed
      command: sudo docker --version
      register: docker_valid
      ignore_errors: yes

- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Create containers folder
      file:
        path: "{{ nas_containers_path }}"
        state: directory

    - name: Uploading containers tars to NAS
      synchronize:
        src: "{{ local_containers_path }}/"
        dest: "{{ nas_containers_path }}"
        # use_ssh_args: yes
        mode: push
        rsync_opts:
          - '--delete'

- hosts: cluster
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Restore the container images
      shell: >
        sudo docker load --input {{ item }}.tar
      args:
        chdir: "{{ nas_containers_path }}"
      with_items:
        - "{{ services_containers_tars }}"

    # - name: validate that the images exists
    #   shell: >
    #     sudo docker image inspect {{ item }}
    #   args:
    #     chdir: "{{ nas_containers_path }}"
    #   with_items:
    #     - "{{ services_containers_images }}"

- hosts: clients
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Restore the container images
      shell: >
        sudo docker load --input {{ item }}.tar
      args:
        chdir: "{{ nas_containers_path }}"
      with_items:
        - "{{ clients_containers_tars }}"

    # - name: validate that the images exists
    #   shell: >
    #     sudo docker image inspect {{ item }}
    #   args:
    #     chdir: "{{ nas_containers_path }}"
    #   with_items:
    #     - "{{ clients_containers_images }}"
