- hosts: swarm_manager
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Tear down existing portainer services
      shell: >
        docker stack rm portainer
      args:
        chdir: "{{ deploy_nas_path }}/deploy"