---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Run Portainer
      shell: >
        sudo docker stack deploy --compose-file ./docker-compose-portainer.yml portainer ;
      args:
        chdir: "{{ deploy_nas_path }}/deploy"
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"