---
- hosts: all
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Check if docker is installed
      command: sudo docker version --format {% raw %}'{{.Server.Version}}'{% endraw %}
      register: docker_version
      ignore_errors: yes

    - name: Check docker version
      fail:
        msg: Wrong docker version installed
      when: docker_version.failed or docker_version.stdout is version('20.10', '<=')

    - name: Check if docker-compose is installed
      command: sudo docker-compose version --short
      register: docker_compose_version
      ignore_errors: yes

    - name: Check docker-compose version
      fail:
        msg: Wrong docker-compose version installed
      when: docker_compose_version.failed or docker_compose_version.stdout is version('2.14', '<=')