---
- hosts:
    - cluster
    - clients
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Make worker nodes leave the Swarm
      shell: docker swarm leave -f
      register: out
      retries: 15
      delay: 45
      until: (out.rc == 0 or 'This node is not part of a swarm' in out.stderr)
      ignore_errors: True

    - name: Prune docker system
      shell: docker system prune --volumes -f


- hosts: swarm_manager
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Make manager nodes leave the Swarm
      shell: docker swarm leave -f
      register: out
      retries: 15
      delay: 45
      until: (out.rc == 0 or 'This node is not part of a swarm' in out.stderr)
      ignore_errors: True

    - name: Undeploy deathstarbench service
      shell: >
        docker stack rm {{ stack }}
      ignore_errors: yes
