---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mms-client
  labels:
    death-star-project: media-microsvc
    app: mms-client
  namespace: media-microsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app: mms-client
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app: mms-client
      name: mms-client
#      annotations:
#        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: mms-client
        image: ubuntu
        command:  ["/bin/sh", "-c"]
        args:
          - apt-get -y update &&
            apt-get -y upgrade &&
            apt-get -y install git dnsutils vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
            luarocks install luasocket &&
            sleep 365d
#        volumeMounts:
#        - mountPath: /root/DeathStarBench
#          name: deathstarbench
        imagePullPolicy: Always
        restartPolicy: Always
#        volumes:
#        - name: deathstarbench
#          PersistentVolumeClaim:
#            claimName: deathstarbench-mms

