visibility_latency_overhead:
  - gather/gcp/socialNetwork/compose-post/us-eu-125/20210913090815

throughput_visibility_latency:
  - gather/gcp/socialNetwork/compose-post/us-eu-100/20210814065624

throughput_latency:
  - gather/gcp/socialNetwork/compose-post/us-eu-100/20210814065624
  - gather/gcp/socialNetwork/compose-post/us-sg-100/20210814065624
  - gather/gcp/socialNetwork/compose-post/us-eu-100-antipode/20210814065624
  - gather/gcp/socialNetwork/compose-post/us-sg-100-antipode/20210814065624

per_inconsistencies:
  - gather/gcp/socialNetwork/compose-post/us-eu-100/20210814065624

throughput_latency_with_consistency_window:
  - gather/gcp/socialNetwork/compose-post/us-eu-100/20210814065624
  - gather/gcp/socialNetwork/compose-post/us-sg-100/20210814065624
  - gather/gcp/socialNetwork/compose-post/us-eu-100-antipode/20210814065624
  - gather/gcp/socialNetwork/compose-post/us-sg-100-antipode/20210814065624