replication_pair: US->EU
services:
  #----------------------------------------------------------
  # Write notifications at EU replica
  #----------------------------------------------------------
  # 4 cores
  social-graph-service: farinheira
  social-graph-redis: farinheira
  #
  # 1 / 2 cores
  social-graph-mongodb: farinheira
  #
  #
  # 5 cores
  write-home-timeline-service-eu: farinheira
  write-home-timeline-service-us: farinheira
  write-home-timeline-rabbitmq-eu: farinheira
  write-home-timeline-rabbitmq-us: farinheira
  home-timeline-redis-eu: farinheira

  #----------------------------------------------------------
  # read notifications at US replica
  #----------------------------------------------------------
  # 4 cores
  home-timeline-redis-us: farinheira
  home-timeline-service: farinheira

  #----------------------------------------------------------
  # write post at replica EU
  #----------------------------------------------------------
  # 4 cores
  post-storage-service-eu: farinheira
  post-storage-memcached-eu: farinheira
  #
  # 1 / 2 cores
  post-storage-mongodb-eu: farinheira

  #----------------------------------------------------------
  # read post at US replica
  #----------------------------------------------------------
  # 4 cores
  post-storage-service-us: farinheira
  post-storage-memcached-us: farinheira
  #
  # 1 / 2 cores
  post-storage-mongodb-us: farinheira

  #----------------------------------------------------------
  # compose posts EU
  #----------------------------------------------------------
  # 5 cores
  compose-post-redis: farinheira
  compose-post-service: farinheira
  unique-id-service: farinheira
  text-service: farinheira
  #
  #
  # 5 cores
  user-timeline-service: farinheira
  user-timeline-redis: farinheira
  user-timeline-mongodb: farinheira
  #
  #
  # 5 cores
  url-shorten-service: farinheira
  url-shorten-memcached: farinheira
  url-shorten-mongodb: farinheira
  user-mention-service: farinheira
  #
  #
  # 1 / 2 cores
  user-service: farinheira
  user-memcached: farinheira
  user-mongodb: farinheira
  #
  #
  # 1 core
  media-service: farinheira
  media-memcached: farinheira
  media-mongodb: farinheira
  media-frontend: farinheira

  #----------------------------------------------------------
  # Coordinator
  #----------------------------------------------------------
  # 1 / 2 cores
  antipode-oracle: farinheira

  #----------------------------------------------------------
  # Frontend EU
  #----------------------------------------------------------
  # 1 / 2 cores
  nginx-thrift: farinheira

  #----------------------------------------------------------
  # Frontend US
  #----------------------------------------------------------
  # 1 / 2 cores
  nginx-thrift-us: farinheira

  #----------------------------------------------------------
  # Admin tasks
  #----------------------------------------------------------
  # 1 / 2 cores
  jaeger: farinheira
  xtrace-server: farinheira
  mongodb-admin: farinheira
  post-storage-mongodb-setup: farinheira
  write-home-timeline-rabbitmq-setup: farinheira

########
#
# total DSB cores: 54
# total DSB cores @ US: 12
# total DSB cores @ EU: 42

# * for 3 zones: 42 * 3 = 126

# total client cores: N clients / 2