replication_pair: US->EU
services:
  #----------------------------------------------------------
  # Write notifications at EU replica
  #----------------------------------------------------------
  # 4 cores
  social-graph-service: saturn2
  social-graph-redis: saturn2
  #
  # 1 / 2 cores
  social-graph-mongodb: saturn2
  #
  #
  # 5 cores
  write-home-timeline-service-eu: saturn2
  write-home-timeline-service-us: saturn2
  write-home-timeline-rabbitmq-eu: saturn2
  write-home-timeline-rabbitmq-us: saturn2
  home-timeline-redis-eu: saturn2

  #----------------------------------------------------------
  # read notifications at US replica
  #----------------------------------------------------------
  # 4 cores
  home-timeline-redis-us: saturn2
  home-timeline-service: saturn2

  #----------------------------------------------------------
  # write post at replica EU
  #----------------------------------------------------------
  # 4 cores
  post-storage-service-eu: saturn2
  post-storage-memcached-eu: saturn2
  #
  # 1 / 2 cores
  post-storage-mongodb-eu: saturn2

  #----------------------------------------------------------
  # read post at US replica
  #----------------------------------------------------------
  # 4 cores
  post-storage-service-us: saturn2
  post-storage-memcached-us: saturn2
  #
  # 1 / 2 cores
  post-storage-mongodb-us: saturn2

  #----------------------------------------------------------
  # compose posts EU
  #----------------------------------------------------------
  # 5 cores
  compose-post-redis: saturn2
  compose-post-service: saturn2
  unique-id-service: saturn2
  text-service: saturn2
  #
  #
  # 5 cores
  user-timeline-service: saturn2
  user-timeline-redis: saturn2
  user-timeline-mongodb: saturn2
  #
  #
  # 5 cores
  url-shorten-service: saturn2
  url-shorten-memcached: saturn2
  url-shorten-mongodb: saturn2
  user-mention-service: saturn2
  #
  #
  # 1 / 2 cores
  user-service: saturn2
  user-memcached: saturn2
  user-mongodb: saturn2
  #
  #
  # 1 core
  media-service: saturn2
  media-memcached: saturn2
  media-mongodb: saturn2
  media-frontend: saturn2

  #----------------------------------------------------------
  # Coordinator
  #----------------------------------------------------------
  # 1 / 2 cores
  antipode-oracle: saturn2

  #----------------------------------------------------------
  # Frontend EU
  #----------------------------------------------------------
  # 1 / 2 cores
  nginx-thrift: saturn2

  #----------------------------------------------------------
  # Frontend US
  #----------------------------------------------------------
  # 1 / 2 cores
  nginx-thrift-us: saturn2

  #----------------------------------------------------------
  # Admin tasks
  #----------------------------------------------------------
  # 1 / 2 cores
  jaeger: saturn2
  xtrace-server: saturn2
  mongodb-admin: saturn2
  post-storage-mongodb-setup: saturn2
  write-home-timeline-rabbitmq-setup: saturn2

# 4 clients used
clients:
  - angainor

manager: angainor

########
#
# total DSB cores: 54
# total DSB cores @ US: 12
# total DSB cores @ EU: 42

# * for 3 zones: 42 * 3 = 126

# total client cores: N clients / 2