---
- hosts: swarm_manager
  any_errors_fatal: true
  gather_facts: no
  become: no
  vars:
    - app: "socialNetwork"
  # vars_files:
  #     - vars.yaml

  tasks:
    - name: Create deploy folder
      file:
        path: "/code/deploy/gcp/"
        state: directory

    - name: Upload portainer compose
      synchronize:
        src: "./docker-compose-portainer.yml"
        dest: "/code/deploy/gcp/"
        use_ssh_args: yes
        mode: push

    - name: Upload ansible inventory
      synchronize:
        src: "./inventory.cfg"
        dest: "/code/deploy/gcp/"
        use_ssh_args: yes
        mode: push

    - name: Upload configurations
      synchronize:
        src: "{{ configuration_filepath }}"
        dest: "/code/deploy/configurations/"
        use_ssh_args: yes
        mode: push

    - name: Upload antipode_manager
      synchronize:
        src: "../../antipode_manager.py"
        dest: "/code/"
        use_ssh_args: yes
        mode: push

    - name: Install pip packages
      shell: >
        pip install {{ item }}
      with_items:
        - plumbum
        - requests
        - pyyaml
        - ansible
        - aiohttp

# deploy prometheus
    - name: Ensures network prometheus configuration dir exists
      file: path=/code/prometheus state=directory

    - name: Create prometheus docker-compose file
      copy:
        src: docker-compose-prometheus.yml
        dest: /code/prometheus/docker-compose.yml
        mode: u=rwx,g=r,o=xr

    - name: Create prometheus configuration
      template:
        src: prometheus.yml.j2
        dest: /code/prometheus/prometheus.yml"
        mode: u=rwx,g=r,o=xr

- hosts: all
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Create '{{ app }}' folder
      file:
        path: "/code/{{ app }}"
        state: directory

    - name: Upload application '{{ app }}' folder
      synchronize:
        src: "../../{{ app }}/"
        dest: "/code/{{ app }}"
        use_ssh_args: yes
        recursive: true
        mode: push

    - name: Pull images from GCP registry
      shell: >
        docker pull gcr.io/pluribus/{{item}} &&
        docker tag gcr.io/pluribus/{{item}} {{item}}
      with_items:
        - mongodb-setup
        - rabbitmq-setup
        - yg397/openresty-thrift:latest
        - yg397/social-network-microservices:antipode
        - redis-im:antipode

# deploy prometheus sensors
- hosts: cluster
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Ensures network prometheus configuration dir exists
      file: path=/code/prometheus state=directory

    - name: Download Prometheus Nodeexporter version 
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.1.1/node_exporter-1.1.1.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-1.1.1.linux-amd64.tar.gz"

    - name: Deploy node exporter bundle and unpack it at the remote nodes 
      unarchive:
        src: "/tmp/node_exporter-1.1.1.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move nodeexporter to installation dir
      command: mv "/tmp/node_exporter-1.1.1.linux-amd64/node_exporter" "/code/prometheus/"
