---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true
  vars:
    - app: socialNetwork

  tasks:
    - name: Init social graph
      # task sleeps to make sure everything is initialized
      shell: >
            sleep 60 ;
            cd /home/jfloff/nas_inesc/antipode/antipode-deathstarbench ;
            ./antipode_manager.py {{ app }} --gsd wkld -f {{ configuration }} -E init-social-graph -r 1
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"
