---
- hosts: all
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Create '{{ app }}' folder
      file:
        path: /code/app
        state: directory

    - name: Upload application
      synchronize:
        src: "{{ deploy_dir }}/"
        dest: /code/app
        use_ssh_args: yes
        recursive: true
        mode: push

    - name: Create deploy folder
      file:
        path: /code/deploy/
        state: directory

    - name: Upload deploy folder
      synchronize:
        src: "{{ deploy_path }}/"
        dest: /code/deploy
        use_ssh_args: yes
        mode: push

- hosts: clients
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Pull images from GCP registry and retag them
      shell: >
        docker pull {{docker_image_namespace}}/{{item}} &&
        docker tag {{docker_image_namespace}}/{{item}} {{item}}
      with_items:
        - wrk2:antipode
        - python-wkld:antipode

- hosts: cluster
  any_errors_fatal: true
  become: no
  gather_facts: no

  tasks:
    - name: Pull images from GCP registry and retag them
      shell: >
        docker pull {{docker_image_namespace}}/{{item}} &&
        docker tag {{docker_image_namespace}}/{{item}} {{item}}
      with_items:
        - mongodb-delayed:4.4.6
        - mongodb-setup:4.4.6
        - rabbitmq-setup:3.8
        - yg397/openresty-thrift:latest
        - yg397/social-network-microservices:antipode
        - redis-im:antipode