---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Run Portainer
      shell: >
        docker stack deploy --compose-file /code/deploy/docker-compose-portainer.yml portainer ;
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"