---
- name: Gather client output files
  hosts: clients
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Check that output file exists
      stat:
        path: "{{ remote_gather_path }}/{{ hostvars[inventory_hostname]['gcp_name'] }}.out"
      register: file_status
      failed_when: not file_status.stat.exists

    - name: Downloading data from remote node
      synchronize:
        src: "{{ remote_gather_path }}/"
        dest: "{{ local_gather_path }}"
        # use_ssh_args: yes
        mode: pull
        rsync_opts:
          - "--chmod=0777"

- name: Gather info.yml
  hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true

  tasks:
    - name: Check that info.yml file exists
      stat:
        path: "{{ remote_gather_path }}/info.yml"
      register: file_status
      failed_when: not file_status.stat.exists

    - name: Downloading data from remote node
      synchronize:
        src: "{{ remote_gather_path }}/info.yml"
        dest: "{{ local_gather_path }}"
        # use_ssh_args: yes
        mode: pull
        rsync_opts:
          - "--chmod=0777"
