---
- hosts: clients
  gather_facts: no
  become: yes
  any_errors_fatal: true

  tasks:
    - name: Remove '{{ wkld_container_name }}' container before running
      shell: >
        docker stop {{ wkld_container_name }} ;
        docker rm {{ wkld_container_name }}
      ignore_errors: True

    - name: Copy wkld-run script
      synchronize:
        src: "{{ local_gather_path }}/wkld-run.sh"
        dest: "/code/deploy/gcp/"
        use_ssh_args: yes
        mode: push

    - name: Start client
      shell: >
        tmux new-session -d -s client_init "./wkld-run.sh && exit";
      args:
        executable: /bin/bash
        chdir: '/code/deploy/gcp'

    - name: Wait for '{{ wkld_container_name }}' container to exit
      shell: >
        docker ps -a --filter 'name={{ wkld_container_name }}' --format {% raw %}'{{.Status}}'{% endraw %}
      register: container_status
      retries: "{{ num_retries | int }}"
      delay: "{{ num_delay | int }}"
      until: ('Exited' in container_status.stdout)

    - name: Remove '{{ wkld_container_name }}' container before running
      shell: >
        docker stop {{ wkld_container_name }} ;
        docker rm {{ wkld_container_name }}
      ignore_errors: True
