---
- hosts: clients
  gather_facts: no
  become: yes
  any_errors_fatal: true

  tasks:
    - name: Create '{{ app }}' folder
      file:
        path: "/code/{{ app }}"
        state: directory

    - name: Upload application '{{ app }}' folder
      synchronize:
        src: "../../{{ app }}/"
        dest: "/code/{{ app }}"
        use_ssh_args: yes
        recursive: true
        mode: push

    - name: Create deploy folder
      file:
        path: "/code/deploy/gcp/"
        state: directory

    - name: Copy wkld-run script
      synchronize:
        src: "./wkld-run.sh"
        dest: "/code/deploy/gcp/"
        use_ssh_args: yes
        mode: push

    - name: Pull images from GCP registry and retag them
      shell: >
        docker pull {{namespace}}/{{item}} &&
        docker tag {{namespace}}/{{item}} {{item}}
      with_items:
        - wrk2:antipode
        - python-wkld:antipode

    - name: Start client
      shell: >
        cd /code/deploy/gcp/ ;
        tmux new-session -d -s client_init "./wkld-run.sh && exit";
      args:
        executable: /bin/bash
