---
- name: Gather wkld output files
  hosts: clients
  gather_facts: no
  become: no
  serial: 1
  any_errors_fatal: true

  tasks:
    - name: Downloading data from remote node
      synchronize:
        src: "/tmp/dsb-wkld-data/"
        dest: "../wkld-data"
        # use_ssh_args: yes
        mode: pull
        rsync_opts:
          - "--chmod=0777"
