---
- hosts: clients
  gather_facts: no
  become: yes
  any_errors_fatal: true

  tasks:
    - name: Kill tmux session and remove '{{ wkld_container_name }}' container before running
      shell: >
        tmux kill-session -t client_init ;
        docker stop {{ wkld_container_name }} ;
        docker rm {{ wkld_container_name }}
      ignore_errors: True

    - name: Copy wkld-run script
      synchronize:
        src: "{{ local_gather_path }}/wkld-run.sh"
        dest: "/code/deploy/gcp/"
        use_ssh_args: yes
        mode: push

    - name: Start client
      shell: >
        tmux new-session -d -s client_init "./wkld-run.sh && exit";
      args:
        executable: /bin/bash
        chdir: '/code/deploy/gcp'

    - name: Wait for '{{ wkld_container_name }}' container to exit
      shell: >
        docker ps -a --filter 'name={{ wkld_container_name }}' --format {% raw %}'{{.Status}}'{% endraw %}
      register: container_status
      retries: 15
      delay: 60
      until: ('Exited' in container_status.stdout)
