---
- hosts: all
  gather_facts: no
  become: no
  any_errors_fatal: true
  vars:
    - stack: deathstarbench
    - app: socialNetwork

  tasks:
    - name: Build deathstarbench images
      shell: >
            cd /home/jfloff/nas_inesc/antipode/antipode-deathstarbench/ ;
            pip3 install -r requirements.txt;
            ./antipode_manager.py {{app}} build
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"
