---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true
  vars_files:
      - vars.yml
  vars:
    # - dest: "/home/jfloff/nas_inesc/antipode/antipode-deathstarbench/deploy/container-images"
    - dest: "../container-images"
    - app: socialNetwork

  tasks:
    - name: validate that the images exists
      shell:  docker image inspect {{item}}
      with_items:
        - "{{ apps[app]['containers'] }}"
        
    - name: Backup container images
      shell: >
            docker save {{item}} | gzip >  {{dest}}/{{ item.replace(':','_').replace('/','_').replace('-','_') }}.tgz
      with_items:
        - "{{ apps[app]['containers'] }}"
  