---
- hosts: all
  gather_facts: no
  become: no
  any_errors_fatal: true
  vars_files:
    - vars.yml
  vars:
    - source: "/home/jfloff/nas_inesc/antipode/antipode-deathstarbench/deploy/container-images"

  tasks:

    - name: Restore the container images
      shell: >
            gzip -d -c  {{source}}/{{ item.replace(':','_').replace('/','_').replace('-','_') }}.tgz | docker load
      with_items:
        - "{{ apps[app]['containers']['to_pull'] | union(apps[app]['containers']['to_build']) }}"


    - name: validate that the images exists
      shell:  docker image inspect {{item}}
      with_items:
        - "{{ apps[app]['containers']['to_pull'] | union(apps[app]['containers']['to_build']) }}"
