---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true
  vars_files:
    - vars.yml
  vars:
    - app: socialNetwork

  tasks:
    - name: Pull  the images of containers used for deathstar benchmark
      shell: >
            docker pull {{item}}
      with_items:
        - "{{ apps[app]['containers']['to_pull'] }}"


    - name: Build the images of containers used for deathstar benchmark
      shell: >
            cd /home/jfloff/nas_inesc/antipode/antipode-deathstarbench ;
            ./antipode_manager.py {{ app }} build
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"
