---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true
  vars:
    - stack: deathstarbench
    - app: socialNetwork

  tasks:
    - name: Run DSB Stack
      shell: >
            cd /home/jfloff/nas_inesc/antipode/antipode-deathstarbench/{{ app }} ;
            docker stack deploy --compose-file ./docker-compose-swarm.yml {{ stack }};
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"

    - name: Make sure DSB stack is all deployed
      shell: >
            {% raw %} docker stack services deathstarbench --format '{{.Name}};{{.Replicas}}' | grep -v '1/1' | wc -l {%endraw%}
      register: stack_status
      # ignores maximum of mongodb-setup
      failed_when: "(stack_status.stdout | int) > 1"