---
- hosts: swarm_manager
  gather_facts: no
  become: no
  any_errors_fatal: true
  vars:
    - stack: deathstarbench
    - app: socialNetwork

  tasks:
    - name: Run DSB Stack
      shell: >
            cd /home/jfloff/nas_inesc/antipode/antipode-deathstarbench/{{ app }} ;
            docker stack deploy --compose-file ./docker-compose-swarm.yml {{ stack }};
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"

    - name: Ensure DSB stack is deployed
      shell: >
           {% raw %} docker stack services deathstarbench --format '{{.Name}};{{.Replicas}}' | grep -v '1/1' | wc -l {%endraw%}
      register: cmd_res
      retries: 6
      delay: 10
      until: (cmd_res.stdout | int) > 1

    - name: Init social graph
      shell: >
            ./antipode_manager.py {{ app }} --gsd wkld init-social-graph -r 1
      register: out
      failed_when: "not(out.rc == 0) or 'fail' in out.stderr"

    # add task to perform init social graphs
