---
  - hosts: clients
    gather_facts: no
    become: no
    any_errors_fatal: true
    vars:
      - app: socialNetwork

    tasks:
      - name: Install needed packages
        shell: >
            luarocks install --local luasocket ;
            luarocks install --local json-lua ;
            luarocks install --local penlight ;
        args:
          executable: /bin/bash

      - name: Start client
        shell: >
            cd /home/jfloff/nas_inesc/antipode/antipode-deathstarbench/deploy/playbooks ;
            tmux new-session -d -s client_init "./wkld-start.sh && exit";
        args:
          executable: /bin/bash
